# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 749ece79cd4c618860a5032c1a6d66b3d726f2c9901175fdfe6018b7dce7c0ffbe752d227adc51b572b267a4a130ce0f388e62c50c09481150d53c9aceec5d30

test:
  secret_key_base: 3b38fa4733fa4153b42e42cd77c2673335ae34c2d35579c2264854ae2c01c5d39ffa616214d2349ef1c039888d4dc87f8cc6cfb9426eb3542c418a80356fc93d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
